### ISSUE TITLE
대화 패턴 추가

### ISSUE THREAD

**Issue by GwangGwang** [GwangGwang/ganeungbot#3]
아직 서포팅안돼는 대화 패턴 코멘트로 적어주세영

**Comment by cj2da** [comment]
어떰?에 variation을 추가
어떨까? 어떤거 같아? 어떻게? 어쩜? 어쩌지? 어쩔까? 어찌함? 등등등

**Comment by yhdks** [comment]
가능해?
가능하니?
가능합니까?
가능해요?
가능하나?
가능하나요?
가능할까?
가능할까요?
가능하냐?
가능함?
가능하냐능?
가능하긔?
